### ISSUE TITLE
WebexMeeting component always renders <video> tag for remote sharing even if nobody shares the screen

### ISSUE THREAD

**Issue by AleksandrDushko** [webex/components#109] opened 2020-07-29 22:40 UTC
WebexMeeting component paired with the WebexSDKAdapter always renders video tag for remote sharing even if nobody actually shares a screen.
As a result, half of the space of WebexMeeting component is occupied by a black rectangular:

![image](https://user-images.githubusercontent.com/68973859/88860644-3752e580-d1ca-11ea-9902-63992bad383d.png)

I think the correct behavior would be to hide video tag for remote sharing if nobody actually shares a screen

**Comment by vinodtv** [comment] 2020-08-19 13:45
@lalli-flores we are using this component and when nothing is shared the screen is still split and one part is empty. Is this something that will be fixed soon?

**Comment by lalli-flores** [comment] 2020-08-19 18:16
@vinodtv, Yes, this is something the team is looking into. Core of the issue is in the SDK, and we've discuss solutions there. At the same time we're looking to see what we can do in the component adapter to fix this issue soon 🤞🏼

**Comment by adamweeks** [comment] 2020-09-15 15:42
This issue has been resolved with SDK adapter [v1.24.0](https://github.com/webex/sdk-component-adapter/releases/tag/v1.24.0).

https://github.com/webex/sdk-component-adapter/pull/81

**Closed by adamweeks** 2020-09-15 15:42 UTC
